### ISSUE TITLE
希望在右下角 添加 一个 “回到顶部”

### ISSUE THREAD

**Issue by ykqmain** [forsigner/fexo#11]
包括电脑和手机，thanks

**Comment by ykqmain** [comment]
分类页面没有回到顶部功能，
另外，我在hexo g之后，终端显示http://0.0.0.0:4000/， 之前我按住cmd双击这个地址就可以打开Safari，现在失效了，要输入 http://localhost:4000才行，请问怎么解决 ？

**Comment by ykqmain** [comment]
要求有点多 ，我觉得加粗不够瞩目， 就是这个 **  **

**Comment by reverland** [comment]
更新发现作者已经加上回到顶部功能了

**Comment by forsigner** [comment]
@ykqmain 不多不多，慢慢完善

**Comment by ykqmain** [comment]
@reverland 
谢谢提醒
我刚更新了一下，发现还是没有。
我是指 “分类” “标签” 页面没有 回到顶部， 而文章内部的确是有的

**Comment by ykqmain** [comment]
@forsigner 
那我就继续说一下建议，(￣▽￣)
“关于”页面的 中心线 会偏左，不知道是不是故意的

很期待 手机页面的优化，这个很需要 (｡-_-｡)

Thanks

**Comment by forsigner** [comment]
@ykqmain 返回顶部已加上配置，默认文章、标签、分类是打开的

```yml
# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false
```

**Comment by ykqmain** [comment]
@forsigner  Thanks

**Comment by forsigner** [comment]
@ykqmain 手机已经基本兼容

**Comment by ykqmain** [comment]
@forsigner  好高的效率 （≧∇≦）

**Comment by ykqmain** [comment]
@forsigner  体验了一下，再反馈一些内容

电脑和手机分开说，我的设置主页是 HOME_NAV

<br><br>

### 电脑

1. 文章内部左边有一条白线

2. 进入文章之后，点上方的 `盒子` , 会回到 首页，

    我希望回到 `archives` 页面

3. `关于` 页面的 中心线 偏左

<br><br><br>

### 手机，Safari

1. 大bug， 文章内部，内容过长的话，后面的文字不可见。图片的右侧同样如此。

2. 手机上，依然需要 “回到顶部” 功能，这也是一个体验问题，iPhone的Safari可以点击顶部回到顶部，但是其他浏览器可能没有这个功能，有时候文章很长，“回到顶部” 这体验就会更舒服

    （上面两条是非常需要，下一条是精益求精的反馈，修复与否无所谓 ＝ ＝ ）

2. 关于盒子
    1. 我用Safari，盒子在页面左下角，Safari的菜单是点击下栏触发，也就是说，我点击 盒子 ，会首先 打开 Safari的菜单，这样一来，我每次需要盒子的时候，需要至少两次点击。或许可以把盒子挪个位置？左上角？或者右上角？

    2. 打开盒子之后，只有点击 `关闭` 才能关闭盒子，根据一些软件的操作，是否可以，`点击任意空白处` 关闭盒子？

<br><br><br>


反馈了这么多，我是一个追求完美的人，可惜自己不会写代码，**麻烦了**  (´･_･`)

**Comment by forsigner** [comment]
@ykqmain 追求完美好啊，我慢慢完善

**Comment by forsigner** [comment]
@ykqmain 大bug 修复了，`点击任意空白处` 已经可以

**Comment by ykqmain** [comment]
@forsigner  `回到顶部` 功能 无效了

**Comment by ykqmain** [comment]
@forsigner  Markdown语法的有序列表不显示 数字

**Comment by forsigner** [comment]
@ykqmain  已修复

**Comment by ykqmain** [comment]
@forsigner 回到顶部不太流畅

手机版，点击 “盒子” 会到达网页底部

**Comment by ykqmain** [comment]
@forsigner  听说1.0了，过来看看。能把链接的颜色改为蓝色吧，不习惯绿色 ＝ ＝

**Comment by ykqmain** [comment]
如果添加背景图片，在手机上的效果比较难看，它直接截取左上角……
能否截取中间的 _(:3」∠)_
不会css

**Comment by ykqmain** [comment]
背景图片的问题大概解决了，通过看w3school又学了一招 😁

```
html.page-home {
  background-image: url('/images/bg.jpg');
  background-repeat: no-repeat;
  background-position:center;
  background-attachment:fixed;
}
```

**Comment by ykqmain** [comment]
如果设置背景图片，那么很容易看出 **搜索** 页面 的bug，你的博客是白色不容易看出来，
网页上半部分正常，下半部分是背景图。
我看了 layout中的`search.ejs`，跟其他的ejs对比了，仍然看不懂。
望修复 _(:3」∠)_

**Comment by ykqmain** [comment]
加粗的文本链接不变颜色，比如这样的，`[**GitHub**](https://github.com)`  应该是加粗的[**GitHub**](https://github.com) ，但是博客中，仅仅是加粗了，并没有显示绿色。虽然可以点击，但是读者可能注意不到，另外，我觉得加粗，这个看上去，不太粗……

**Comment by ykqmain** [comment]
友链页面也有  无法覆盖背景图片 的问题

**Comment by forsigner** [comment]
@ykqmain 加粗已经修复

**Comment by forsigner** [comment]
背景图页修复，居中可以这样：
```css
html.page-home {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-image: url('/images/bg.jpg');
  background-color: transparent;
  background-size: cover;
  background-position: center center;
  background-repeat: no-repeat;

  /*background: linear-gradient( #1abc9c, transparent), linear-gradient( 90deg, skyblue, transparent), linear-gradient( -90deg, coral, transparent);*/
  /*background-blend-mode: screen;*/

  /*background: linear-gradient(to left, #5f2c82, #49a09d);*/
}

```
