### ISSUE TITLE
希望改善文章内的目录，添加文章底部“上一篇”和“下一篇”

### ISSUE THREAD

**Issue by YangDejie** [forsigner/fexo#38]
1.希望每一篇文章的目录都能浮动，因为如果目录很简短，但文章很长的话，翻到下面时就看不到文章的目录了。
2.希望每篇文章底部添加“上（下）一篇：XXX”
3.我看到已经有人提问快速滚回顶部的浮动按钮
感谢

**Comment by ssbunny** [comment]
我用safari 9.0.2 (11601.3.9) 使用目录的话，控制台会有一个JS错误，但使用起来正常。也没细看原因（毕竟有一部分JS是压缩的）。希望项目主人有时间看看。

**Comment by forsigner** [comment]
能否截图，我在我这边Safari出现不了，或者有没有blog地址我看看

**Comment by forsigner** [comment]
@YangDejie 上一篇下一篇 我也可以加上哈  分享的话我再看看

**Comment by scarletsky** [comment]
怎么会 @ 到我了呢...

**Comment by YangDejie** [comment]
@forsigner 好感+1000000000

**Comment by ssbunny** [comment]
@forsigner 顺便一说，我把目录关了，因为离正文太近，目录多的时候感觉有点乱。
先暂时打开了目录，你看看[这个页面](http://wangshanshan.info/posts/201512260/) 在你那里是不是有问题。

**Comment by forsigner** [comment]
@scarletsky @错人了 囧

**Comment by forsigner** [comment]
@ssbunny 在我这边的效果：

![Markdown](http://i1.piimg.com/1949/b587a21e3e80c701.png)

**Comment by ssbunny** [comment]
@forsigner 我发的链接是给你看控制台错误的，这个页面我这里也正常显示啊。你可能被我的“顺便一说”搞乱了。

**Comment by ChenJiaH** [comment]
2.希望每篇文章底部添加“上（下）一篇：XXX”

@forsigner 辛苦了，加上这个我感觉就perfect了~

**Comment by forsigner** [comment]
@YangDejie @ChenJiaH 终于抽时间加上下一篇功能，配置如下
``` 
post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

```
